# Build the React App
FROM node:18 AS frontend-builder

WORKDIR /app

# Copy the frontend
COPY graphql-react-app /app

# Install dependencies and build
RUN npm install && npm run build

# Build Spring Boot
FROM maven:3.8.5-openjdk-17 AS backend-builder

WORKDIR /app

# Copy the Maven
COPY pom.xml .
COPY src ./src

# Package Spring Boot 
RUN mvn clean package -DskipTests

# Run the Application
FROM openjdk:17-jdk-slim

WORKDIR /app

# Copy the built Spring Boot
COPY --from=backend-builder /app/target/*.jar app.jar

# Copy the built React frontend
COPY --from=frontend-builder /app/build ./public

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "app.jar"]
